//! Renders the project dictionary files in `docs/dictionary/` as one Markdown page.
//! Usage: `gen-dictionary [--out PATH]...`
const std = @import("std");
const Io = std.Io;

const Section = struct {
    file: []const u8,
    title: []const u8,
    intro: []const u8,
    /// Lines with `a -> b` or `a: b` become a two-column table.
    table: bool,
};

const sections = [_]Section{
    .{ .file = "technical_nouns.txt", .title = "Technical nouns", .intro = "Nouns that name project concepts (ASD-STE100 rule 1.5, categories 15 and 19). Use one noun for one concept.", .table = false },
    .{ .file = "technical_verbs.txt", .title = "Technical verbs", .intro = "Verbs that name project actions (rule 1.12, category 2).", .table = false },
    .{ .file = "restricted_words.txt", .title = "Restricted words", .intro = "Approved words that have one meaning in this project.", .table = true },
    .{ .file = "project_word_list.txt", .title = "Project word list", .intro = "Words that this project does not use in prose, with the replacement.", .table = true },
    .{ .file = "ing_allowlist.txt", .title = "Approved -ing words", .intro = "Technical nouns and adjectives that end in -ing (rule 3.5).", .table = false },
};

/// A comment such as `# PN-1 protocol nouns` names a group.
fn isGroupComment(line: []const u8) bool {
    return line.len > 5 and line[1] == ' ' and line[2] == 'P' and (line[3] == 'N' or line[3] == 'V') and line[4] == '-';
}

pub fn main(init: std.process.Init) !u8 {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    var outs: std.ArrayList([]const u8) = .empty;
    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--out") and i + 1 < args.len) {
            i += 1;
            try outs.append(arena, args[i]);
        } else {
            std.debug.print("gen-dictionary: unknown argument {s}\n", .{args[i]});
            return 2;
        }
    }
    var dir = try Io.Dir.cwd().openDir(io, "docs/dictionary", .{});
    defer dir.close(io);
    var aw: Io.Writer.Allocating = .init(arena);
    const w = &aw.writer;
    try w.writeAll("# Dictionary\n\n<!-- ste: descriptive | generated by zig build gen-dictionary from docs/dictionary/*.txt -->\n\n");
    try w.writeAll("This page is the project dictionary for the [Style Guide](Style-Guide-STE). The linter `zig build lint-docs` reads the same files.\n\n");
    var words: usize = 0;
    for (sections) |s| {
        const text = try dir.readFileAlloc(io, s.file, arena, .limited(1 << 20));
        try w.print("## {s}\n\n{s}\n\n", .{ s.title, s.intro });
        if (s.table) try w.writeAll("| Word | Meaning or replacement |\n| --- | --- |\n");
        var lines = std.mem.splitScalar(u8, text, '\n');
        var group: ?[]const u8 = null;
        while (lines.next()) |raw| {
            const line = std.mem.trim(u8, raw, " \t\r");
            if (line.len == 0) continue;
            if (line[0] == '#') {
                // A comment that names a category becomes a sub-heading in list sections.
                if (!s.table and isGroupComment(line)) {
                    group = std.mem.trim(u8, line[1..], " ");
                    try w.print("\n**{s}**\n\n", .{group.?});
                }
                continue;
            }
            words += 1;
            if (s.table) {
                const sep: usize = std.mem.indexOf(u8, line, " -> ") orelse (std.mem.indexOfScalar(u8, line, ':') orelse line.len);
                const key = std.mem.trim(u8, line[0..sep], " ");
                const rest_start = if (std.mem.indexOf(u8, line, " -> ") != null) sep + 4 else @min(sep + 1, line.len);
                const value = std.mem.trim(u8, line[rest_start..], " ");
                try w.print("| {s} | {s} |\n", .{ key, value });
            } else {
                try w.print("- {s}\n", .{line});
            }
        }
        try w.writeAll("\n");
    }
    const page = try aw.toOwnedSlice();
    for (outs.items) |path| try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = page });
    std.debug.print("gen-dictionary: {d} words, {d} files written\n", .{ words, outs.items.len });
    return 0;
}
