//! Renders `docs/bibliography.zon` as a Markdown page and checks it.
//! Usage: `gen-bibliography [--check] [--out PATH]...`
//! `--check` fails on duplicate ids, on `file://` URLs and on URLs without a scheme.
//! Every `--out` path receives the rendered page. The wiki page uses one heading per key,
//! so `[KEY](Bibliography#key)` links resolve on GitHub.
const std = @import("std");
const Io = std.Io;

const Entry = struct {
    id: []const u8,
    title: []const u8,
    author: []const u8 = "",
    publisher: []const u8 = "",
    date: []const u8 = "",
    url: []const u8,
    accessed: []const u8 = "",
    category: []const u8 = "other",
    note: []const u8 = "",
};

const category_titles = [_][2][]const u8{
    .{ "mcp", "Model Context Protocol" },
    .{ "jsonrpc", "JSON-RPC and JSON Schema" },
    .{ "http", "HTTP, TLS and URIs" },
    .{ "http2", "HTTP/2 and HPACK" },
    .{ "sse", "Server-Sent Events" },
    .{ "oauth", "OAuth 2.1 and OpenID Connect" },
    .{ "grpc", "gRPC and the MCP transport discussions" },
    .{ "protobuf", "Protocol Buffers" },
    .{ "sdk", "Official and community SDKs" },
    .{ "zig", "Zig" },
    .{ "ste", "ASD-STE100 Simplified Technical English" },
    .{ "github", "GitHub" },
    .{ "other", "Other" },
};

pub fn main(init: std.process.Init) !u8 {
    const gpa = init.gpa;
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    var check = false;
    var outs: std.ArrayList([]const u8) = .empty;
    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--check")) {
            check = true;
        } else if (std.mem.eql(u8, args[i], "--out") and i + 1 < args.len) {
            i += 1;
            try outs.append(arena, args[i]);
        } else {
            std.debug.print("gen-bibliography: unknown argument {s}\n", .{args[i]});
            return 2;
        }
    }

    const text = try Io.Dir.cwd().readFileAllocOptions(io, "docs/bibliography.zon", arena, .limited(4 << 20), .of(u8), 0);
    const entries = std.zon.parse.fromSliceAlloc([]const Entry, gpa, text, null, .{}) catch |e| {
        std.debug.print("gen-bibliography: cannot parse docs/bibliography.zon: {t}\n", .{e});
        return 1;
    };
    defer std.zon.parse.free(gpa, entries);

    var problems: usize = 0;
    if (check) problems = checkEntries(entries);

    const sorted = try arena.dupe(Entry, entries);
    std.mem.sort(Entry, sorted, {}, lessThan);
    const page = try render(arena, sorted);
    for (outs.items) |path| {
        try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = page });
    }
    std.debug.print("gen-bibliography: {d} entries, {d} problems, {d} files written\n", .{ entries.len, problems, outs.items.len });
    return if (problems == 0) 0 else 1;
}

fn checkEntries(entries: []const Entry) usize {
    var problems: usize = 0;
    for (entries, 0..) |e, i| {
        if (std.mem.startsWith(u8, e.url, "file://")) {
            std.debug.print("::error::{s}: local file URL is not permitted\n", .{e.id});
            problems += 1;
        }
        if (!std.mem.startsWith(u8, e.url, "https://") and !std.mem.startsWith(u8, e.url, "http://")) {
            std.debug.print("::error::{s}: URL has no http scheme: {s}\n", .{ e.id, e.url });
            problems += 1;
        }
        for (e.id) |c| if (!(std.ascii.isUpper(c) or std.ascii.isDigit(c) or c == '-' or c == '.')) {
            std.debug.print("::error::{s}: keys use uppercase letters, digits, '-' and '.'\n", .{e.id});
            problems += 1;
            break;
        };
        for (entries[i + 1 ..]) |other| if (std.mem.eql(u8, e.id, other.id)) {
            std.debug.print("::error::{s}: duplicate key\n", .{e.id});
            problems += 1;
        };
    }
    return problems;
}

fn categoryRank(category: []const u8) usize {
    for (category_titles, 0..) |c, i| if (std.mem.eql(u8, c[0], category)) return i;
    return category_titles.len;
}

fn lessThan(_: void, a: Entry, b: Entry) bool {
    const ra = categoryRank(a.category);
    const rb = categoryRank(b.category);
    if (ra != rb) return ra < rb;
    return std.mem.lessThan(u8, a.id, b.id);
}

fn render(arena: std.mem.Allocator, entries: []const Entry) ![]u8 {
    var aw: Io.Writer.Allocating = .init(arena);
    const w = &aw.writer;
    try w.writeAll("# Bibliography\n\n<!-- ste: descriptive | generated by zig build gen-bibliography from docs/bibliography.zon -->\n\n");
    try w.writeAll("This page lists every source that the wiki, the README and the design documents cite. Each entry has a stable key. Other pages link to a key with `[KEY](Bibliography#key)`.\n\n");
    var current: ?[]const u8 = null;
    for (entries) |e| {
        if (current == null or !std.mem.eql(u8, current.?, e.category)) {
            current = e.category;
            const rank = categoryRank(e.category);
            const title = if (rank < category_titles.len) category_titles[rank][1] else e.category;
            try w.print("## {s}\n\n", .{title});
        }
        try w.print("### {s}\n\n", .{e.id});
        try w.print("- Title: {s}\n", .{e.title});
        if (e.author.len > 0) try w.print("- Author: {s}\n", .{e.author});
        if (e.publisher.len > 0) try w.print("- Publisher: {s}\n", .{e.publisher});
        if (e.date.len > 0) try w.print("- Date: {s}\n", .{e.date});
        try w.print("- URL: <{s}>\n", .{e.url});
        if (e.accessed.len > 0) try w.print("- Accessed: {s}\n", .{e.accessed});
        if (e.note.len > 0) try w.print("- Note: {s}\n", .{e.note});
        try w.writeAll("\n");
    }
    return aw.toOwnedSlice();
}

test "check finds duplicates and local urls" {
    const entries = [_]Entry{
        .{ .id = "A-1", .title = "a", .url = "https://example.com/a" },
        .{ .id = "A-1", .title = "b", .url = "file:///tmp/b" },
        .{ .id = "bad key", .title = "c", .url = "ftp://x" },
    };
    try std.testing.expectEqual(4, checkEntries(&entries));
}
