//! The gen-dictionary tool writes the word lists of `docs/dictionary/` as one Markdown page.
//!
//! Usage: `gen-dictionary [--check] [--out PATH]...`
//!
//! With `--check`, the tool writes nothing. It fails when a file of `--out` differs from the page.
const std = @import("std");
const Io = std.Io;
const Allocator = std.mem.Allocator;

const Layout = enum {
    /// One item for each line.
    list,
    /// Lines with `a -> b` become a table with two columns.
    arrow_table,
    /// Lines with `a: b` become a table with two columns.
    colon_table,
};

const Section = struct {
    file: []const u8,
    title: []const u8,
    intro: []const u8,
    layout: Layout,
    /// The column titles of a table.
    columns: [2][]const u8 = .{ "Word", "Meaning or replacement" },
};

const sections = [_]Section{
    .{ .file = "technical_nouns.txt", .title = "Technical nouns", .intro = "Nouns that name project concepts (ASD-STE100 rule 1.5, categories 15 and 19). Use one noun for one concept.", .layout = .list },
    .{ .file = "technical_verbs.txt", .title = "Technical verbs", .intro = "Verbs that name project actions (rule 1.12, category 2).", .layout = .list },
    .{ .file = "approved_verbs.txt", .title = "Approved verbs", .intro = "General verbs that the prose of the project uses. Use the simple present, the simple past or the future of these verbs (rule 3.4).", .layout = .list },
    .{ .file = "restricted_words.txt", .title = "Restricted words", .intro = "Approved words that have one meaning in this project.", .layout = .colon_table },
    .{ .file = "project_word_list.txt", .title = "Project word list", .intro = "Words that this project does not use in prose, with the replacement (rule 1.1).", .layout = .arrow_table },
    .{ .file = "synonyms.txt", .title = "Synonyms", .intro = "Terms that the project does not use, with the project term (PRJ-4). One concept has one term.", .layout = .arrow_table, .columns = .{ "Term", "Project term" } },
    .{ .file = "phrasal_verbs.txt", .title = "Phrasal verbs", .intro = "Phrasal verbs that the project does not use, with a verb of one word (PRJ-5).", .layout = .arrow_table, .columns = .{ "Phrasal verb", "Replacement" } },
    .{ .file = "spelling_us.txt", .title = "US spelling", .intro = "The project uses US spelling (PRJ-3). The table gives the British spelling and the US spelling.", .layout = .arrow_table, .columns = .{ "British spelling", "US spelling" } },
    .{ .file = "abbreviations.txt", .title = "Abbreviations", .intro = "Abbreviations and names with a fixed case that the prose can use (PRJ-2). A sentence can start with a name of this list that starts with a lowercase letter (PRJ-1).", .layout = .colon_table, .columns = .{ "Abbreviation", "Meaning" } },
    .{ .file = "participles.txt", .title = "Participles as adjectives", .intro = "Past participles that tell a state after \"is\" or \"are\" (rule 3.6).", .layout = .list },
    .{ .file = "ing_allowlist.txt", .title = "Approved -ing words", .intro = "Technical nouns and adjectives that end in -ing (rule 3.5).", .layout = .list },
};

/// A comment such as `# PN-1 protocol nouns` names a group of words.
fn isGroupComment(line: []const u8) bool {
    if (line.len < 6 or line[0] != '#' or line[1] != ' ') return false;
    var i: usize = 2;
    while (i < line.len and std.ascii.isUpper(line[i])) i += 1;
    return i >= 4 and i + 1 < line.len and line[i] == '-' and std.ascii.isDigit(line[i + 1]);
}

/// Writes the dictionary page and returns the number of entries.
fn render(arena: Allocator, io: Io, dir: Io.Dir, w: *Io.Writer) !usize {
    try w.writeAll("# Dictionary\n\n<!-- ste: descriptive | generated by zig build gen-dictionary from docs/dictionary/*.txt -->\n\n");
    try w.writeAll("This page is the project dictionary for the [Style Guide](Style-Guide-STE). The linter `zig build lint-docs` reads the same files. The lists are the work of this project. They do not copy the dictionary of ASD-STE100.\n\n");
    var entries: usize = 0;
    for (sections) |s| {
        const text = dir.readFileAlloc(io, s.file, arena, .limited(1 << 20)) catch |err| switch (err) {
            error.FileNotFound => continue,
            else => |e| return e,
        };
        try w.print("## {s}\n\n{s}\n\n", .{ s.title, s.intro });
        if (s.layout != .list) try w.print("| {s} | {s} |\n| --- | --- |\n", .{ s.columns[0], s.columns[1] });
        var lines = std.mem.splitScalar(u8, text, '\n');
        while (lines.next()) |raw| {
            const line = std.mem.trim(u8, raw, " \t\r");
            if (line.len == 0) continue;
            if (line[0] == '#') {
                // A comment that names a group becomes a label in list sections.
                if (s.layout == .list and isGroupComment(line)) try w.print("\n**{s}**\n\n", .{std.mem.trim(u8, line[1..], " ")});
                continue;
            }
            entries += 1;
            switch (s.layout) {
                .list => try w.print("- {s}\n", .{line}),
                .arrow_table, .colon_table => {
                    const separator = if (s.layout == .arrow_table) " -> " else ": ";
                    const sep = std.mem.find(u8, line, separator) orelse line.len;
                    const key = std.mem.trim(u8, line[0..sep], " ");
                    const value = if (sep < line.len) std.mem.trim(u8, line[sep + separator.len ..], " ") else "";
                    try w.print("| {s} | {s} |\n", .{ key, value });
                },
            }
        }
        try w.writeAll("\n");
    }
    return entries;
}

pub fn main(init: std.process.Init) !u8 {
    const arena = init.arena.allocator();
    const io = init.io;
    const args = try init.minimal.args.toSlice(arena);
    var outs: std.ArrayList([]const u8) = .empty;
    var check = false;
    var i: usize = 1;
    while (i < args.len) : (i += 1) {
        if (std.mem.eql(u8, args[i], "--out") and i + 1 < args.len) {
            i += 1;
            try outs.append(arena, args[i]);
        } else if (std.mem.eql(u8, args[i], "--check")) {
            check = true;
        } else {
            std.debug.print("gen-dictionary: unknown argument {s}\n", .{args[i]});
            return 2;
        }
    }
    var dir = try Io.Dir.cwd().openDir(io, "docs/dictionary", .{});
    defer dir.close(io);
    var aw: Io.Writer.Allocating = .init(arena);
    const entries = try render(arena, io, dir, &aw.writer);
    const page = aw.written();
    var stale: usize = 0;
    for (outs.items) |path| {
        if (check) {
            const current = Io.Dir.cwd().readFileAlloc(io, path, arena, .limited(16 << 20)) catch "";
            if (!std.mem.eql(u8, current, page)) {
                std.debug.print("gen-dictionary: {s} is not current. Run zig build gen-dictionary.\n", .{path});
                stale += 1;
            }
        } else {
            try Io.Dir.cwd().writeFile(io, .{ .sub_path = path, .data = page });
        }
    }
    std.debug.print("gen-dictionary: {d} entries, {d} files {s}\n", .{ entries, outs.items.len, if (check) "checked" else "written" });
    return if (stale > 0) 1 else 0;
}

test "group comments" {
    try std.testing.expect(isGroupComment("# PN-1 protocol nouns"));
    try std.testing.expect(isGroupComment("# ING-3 words"));
    try std.testing.expect(!isGroupComment("# Format: word -> replacement."));
    try std.testing.expect(!isGroupComment("# A-1 x"));
}

test "render gives every section" {
    var arena_state: std.heap.ArenaAllocator = .init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var dir = try Io.Dir.cwd().openDir(std.testing.io, "docs/dictionary", .{});
    defer dir.close(std.testing.io);
    var aw: Io.Writer.Allocating = .init(arena);
    const entries = try render(arena, std.testing.io, dir, &aw.writer);
    try std.testing.expect(entries > 100);
    try std.testing.expect(std.mem.find(u8, aw.written(), "## US spelling") != null);
    try std.testing.expect(std.mem.find(u8, aw.written(), "| behaviour | behavior |") != null);
}
